package edu.wpi.first.wpilibj.templates;



public class RobotMap {
  
    public static final int LEFT_MOTOR = 1;
    public static final int RIGHT_MOTOR = 2;
    public static final int PULLBACK_WINCH_ONE = 3;
    public static final int PULLBACK_WINCH_TWO = 4;
    public static final int PICKUP_DEPLOY_ONE = 5;
    public static final int PICKUP_DEPLOY_TWO = 6;
    public static final int SHOOTER_DEPLOY_ONE = 7;
    public static final int SHOOTER_DEPLOY_TWO = 8;
    public static final int PNUMATIC_SHIFT_ONE = 9;
    public static final int PNEMATIC_SHIFT_TWO = 10;
    public static final int PICKUP_ROLLER = 11;
    public static final int PICKUP_SENSOR = 1;
    public static final int SHOOTER_LIMIT = 2;
    public static final int ENC_RIGHT_ONE = 3;
    public static final int ENC_RIGHT_TWO = 4;
    public static final int ENC_LEFT_ONE = 5;
    public static final int ENC_LEFT_TWO = 6;
    
   // public double Joystick () {}
}
